---
title: "emmadll"
format: html
---

## Loading census data
```{r}
#install.packages("tidycensus")
#install.packages("purrr")
#install.packages("scales")
#install.packages("patchwork")
library(patchwork)
library(tidycensus)
library(purrr)
library(dplyr)
library(ggplot2)
library(scales)

variables <- load_variables(2024, "acs5")

years <- list(2024, 2020, 2016, 2012)

english_only_pop <- map_dfr(
  years,
  ~ get_acs(
    geography = "us", 
    variables = "B16001_002", 
    year = .x, 
    survey = "acs5"),
  .id = "year")

total_pop <- map_dfr(
  years,
  ~ get_acs(
    geography = "us", 
    variables = "B16001_001", 
    year = .x, 
    survey = "acs5"),
  .id = "year")

english_only_pop_ma <- map_dfr(
  years,
  ~ get_acs(
    geography = "state", 
    state = "MA",
    variables = "B16001_002", 
    year = .x, 
    survey = "acs5"),
  .id = "year")

total_pop_ma <- map_dfr(
  years,
  ~ get_acs(
    geography = "state", 
    state = "MA",
    variables = "B16001_001", 
    year = .x, 
    survey = "acs5"),
  .id = "year")
```

## Calculating US Bilingual Population
```{r}
bilingual_pop <- english_only_pop |>
  left_join(
    total_pop|>
      select(year, GEOID, NAME, totalpop = estimate),
    by = c("year", "GEOID", "NAME"))

bilingual_pop <- bilingual_pop |>
  mutate(bilingualpop = totalpop-estimate)

bilingual_pop <- bilingual_pop |>
  mutate(percent_bilingual = bilingualpop / totalpop * 100)

bilingual_pop$year <- as.character(bilingual_pop$year)
bilingual_pop[1, "year"] <- as.character("2020-2024")
bilingual_pop[2, "year"] <- as.character("2016-2020")
bilingual_pop[3, "year"] <- as.character("2012-2016")
bilingual_pop[4, "year"] <- as.character("2008-2012")
```

## Calculating MA Bilingual Population
```{r}
bilingual_pop_ma <- english_only_pop_ma |>
  left_join(
    total_pop_ma|>
      select(year, GEOID, NAME, totalpop = estimate),
    by = c("year", "GEOID", "NAME"))

bilingual_pop_ma <- bilingual_pop_ma |>
  mutate(bilingualpop = totalpop-estimate)

bilingual_pop_ma <- bilingual_pop_ma |>
  mutate(percent_bilingual = bilingualpop / totalpop * 100)

bilingual_pop_ma$year <- as.character(bilingual_pop_ma$year)
bilingual_pop_ma[1, "year"] <- as.character("2020-2024")
bilingual_pop_ma[2, "year"] <- as.character("2016-2020")
bilingual_pop_ma[3, "year"] <- as.character("2012-2016")
bilingual_pop_ma[4, "year"] <- as.character("2008-2012")
```

## Plots for United States
```{r}
p1 <- ggplot(bilingual_pop, aes(x = year, y = bilingualpop, group = 1)) +
  geom_line() +
  geom_point() + # with or without the geom_point?
  scale_y_continuous(labels = label_number(scale_cut = cut_short_scale())) +
  labs(x = "ACS 5 Year Survey Range",
       y = "Bilingual Population in the United States (Millions)",
       title = "Total Bilingual Population, United States, 2008-2024") +
  theme_minimal() 

p2 <- ggplot(bilingual_pop, aes(x = year, y = percent_bilingual, group = 1)) +
  geom_line() +
  labs(x = "ACS 5 Year Survey Range", 
       y = "% Bilingual Population",
       title = "Percent Bilingual Population United States, 2008-2024") +
  theme_minimal()
```

## Plots for MA
```{r}
p3 <- ggplot(bilingual_pop_ma, aes(x = year, y = bilingualpop, group = 1)) +
  geom_line() +
  scale_y_continuous(labels = label_number(scale_cut = cut_short_scale()),
                     limits = c(1300000, 1700000)) +
  labs(x = "ACS 5 Year Survey Range",
       y = "Bilingual Population in MA (Millions)",
       title = "Total Bilingual Population, Massachusetts, 2008-2024") +
  theme_minimal() 

p4 <- ggplot(bilingual_pop_ma, aes(x = year, y = percent_bilingual, group = 1)) +
  geom_line() + 
  labs(x = "ACS 5 Year Survey Range", 
       y = "% MA Bilingual Population",
       title = "Percent Bilingual Population, Massachusetts, 2008-2024") +
  theme_minimal() 

p1 / p3
p2 / p4
```