---
title: "PIR Summary Stats - MA"
format: html
editor: source
---

```{r}
library(tidyverse)
library(readxl)

pir_import_a <- function(year) {
  
  filename <- paste0("data/pir_export_", year, ".xlsx")
  var
  pir_data <- read_excel(filename, sheet = 1, skip = 1)
  pir_data <- pir_data |>
    mutate(pir_year = year) |>
    select(pir_year, Region:City, A.10.g, A.13.d, A.27) |>
    filter(Region != "Totals")
}

pir_import_b <- function(year) {
  
  filename <- paste0("data/pir_export_", year, ".xlsx")
  var
  pir_data <- read_excel(filename, sheet = 2, skip = 1)
  pir_data <- pir_data |>
    mutate(pir_year = year) |>
    select(pir_year, Region:City, B.14) |>
    filter(Region != "Totals")
}

pir_import_c <- function(year) {
  
  filename <- paste0("data/pir_export_", year, ".xlsx")
  var
  pir_data <- read_excel(filename, sheet = 3, skip = 1)
  pir_data <- pir_data |>
    mutate(pir_year = year) |>
    select(pir_year, Region:City, C47) |>
    filter(Region != "Totals")
}

year <- c(2021:2025)


pir_a <- map_df(year, pir_import_a)
pir_b <- map_df(year, pir_import_b)
pir_c <- map_df(year, pir_import_c)

```

## Data Quality Assessments

> Need to come up with meaningful breaks

```{r}
pir_a <- pir_a |>
  mutate(size_binned = cut(A.10.g,
                           breaks=c(0,100,500,1000,1500,2000),
                           labels=c("0-100",">100-500",">500-1000",">1000-1500", "Greater than 1500")))

pir_a |>
  filter(State == "MA") |>
  ggplot(aes(x = size_binned, y = A.13.d)) +
  geom_jitter(alpha = 0.5)
```


## Homeless Enrollment in MA vs Other States

```{r}
pir_a |>
  filter(pir_year == 2025) |>
  group_by(State) |>
  summarize(total_child_enroll = sum(A.10.g), 
      total_homeless_enroll = sum(A.13.d),
      percent_homeless = total_homeless_enroll / total_child_enroll * 100) |>
  arrange(desc(percent_homeless))
```

## Homeless Enrollment Over Time

```{r}
options(scipen = 999)
pir_a |>
  filter(State == "MA") |>
  group_by(pir_year) |>
  summarize(homeless_children = sum(A.13.d),
            total_child_enroll = sum(A.10.g),
      percent_homeless = homeless_children / total_child_enroll * 100) |>
  ggplot(aes(x = pir_year, y = percent_homeless)) +
  geom_line() +
  scale_x_continuous(breaks = min(pir_a$pir_year):max(pir_a$pir_year)) +
  scale_y_continuous(limits = c(0, 15)) +
  labs(x = "Year", 
       y = "% Enrolled Homeless Children", 
       title = paste("Head Start PIR, MA,",
                     min(pir_a$pir_year), 
                     "-" , 
                     max(pir_a$pir_year))) +
  theme_minimal() 

pir_a |>
  filter(State == "MA") |>
  group_by(pir_year, `Type`) |>
  summarize(homeless_children = sum(A.13.d),
            total_child_enroll = sum(A.10.g),
      percent_homeless = homeless_children / total_child_enroll * 100) |>
  ggplot(aes(x = pir_year, y = percent_homeless)) +
  geom_line() +
  facet_wrap(vars(`Type`)) +
  scale_x_continuous(breaks = min(pir_a$pir_year):max(pir_a$pir_year)) +
  labs(x = "Year", 
       y = "% Enrolled Homeless Children", 
       title = paste("Head Start PIR, MA,",
                     min(pir_a$pir_year), 
                     "-" , 
                     max(pir_a$pir_year))) +
  theme_minimal() 

```

#dual language learners 
```{r} 
pir_a |>
  filter(State == "MA") |>
  group_by(pir_year) |>
  summarize(dual_lang_learners = sum(A.27),
            total_child_enroll = sum(A.10.g),
      percent_dual = dual_lang_learners / total_child_enroll * 100) |>
  ggplot(aes(x = pir_year, y = percent_dual)) +
  geom_line() +
  scale_x_continuous(breaks = min(pir_a$pir_year):max(pir_a$pir_year)) +
  scale_y_continuous(limits = c(0, 100)) +
  labs(x = "Year", 
       y = "% Enrolled Dual Language Learners", 
       title = paste("Head Start PIR, MA,",
                     min(pir_a$pir_year), 
                     "-" , 
                     max(pir_a$pir_year))) +
  theme_minimal() 

pir_a |>
  filter(State == "MA") |>
  group_by(pir_year, `Type`) |>
  summarize(dual_lang_learners = sum(A.27),
            total_child_enroll = sum(A.10.g),
      percent_dual = dual_lang_learners / total_child_enroll * 100) |>
  ggplot(aes(x = pir_year, y = percent_dual)) +
  geom_line() +
  facet_wrap(vars(`Type`)) +
  scale_x_continuous(breaks = min(pir_a$pir_year):max(pir_a$pir_year)) +
  labs(x = "Year", 
       y = "% Enrolled Dual Language Learners", 
       title = paste("Head Start PIR, MA,",
                     min(pir_a$pir_year), 
                     "-" , 
                     max(pir_a$pir_year))) +
  theme_minimal() 

```

#bilingual teachers
```{r} 
pir_b |>
  filter(State == "MA") |>
  group_by(pir_year) |>
  summarize(bilingual_teachers = sum(B.14)) |>
  ggplot(aes(x = pir_year, y = bilingual_teachers)) +
  geom_line() +
  scale_x_continuous(breaks = min(pir_a$pir_year):max(pir_a$pir_year)) +
  scale_y_continuous(limits = c(0, 1000)) +
  labs(x = "Year", 
       y = "Number of Bilingual Teachers", 
       title = paste("Head Start PIR, MA,",
                     min(pir_a$pir_year), 
                     "-" , 
                     max(pir_a$pir_year))) +
  theme_minimal() 

pir_b |>
  filter(State == "MA") |>
  group_by(pir_year, `Type`) |>
  summarize(bilingual_teachers = sum(B.14)) |>
  ggplot(aes(x = pir_year, y = bilingual_teachers)) +
  geom_line() +
  facet_wrap(vars(`Type`)) +
  scale_x_continuous(breaks = min(pir_a$pir_year):max(pir_a$pir_year)) +
  labs(x = "Year", 
       y = "Number of Bilingual Teachers", 
       title = paste("Head Start PIR, MA,",
                     min(pir_a$pir_year), 
                     "-" , 
                     max(pir_a$pir_year))) +
  theme_minimal() 

```